# Generated by Django 5.2.6 on 2025-10-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above to Reacd Blog Post. . .', max_length=225),
        ),
    ]
